---
title: "About This Website"
---

Eric Stone is a professor of psychology at Wake Forest University. He has been teaching at Wake Forest since 1994. He earned his Ph.D. in Cognition and Perception along with an M.A. in Applied Statistics from the University of Michigan, Ann Arbor, in 1994. (Mason was `r 1994-1989` years old). His undergraduate studies culminated in a B.A. in Mathematical Sciences and Psychology, with honors, magna cum laude, from the University of Delaware in 1987 (Mason was `r 1987-1989` years old).. His research interests include judgment and decision-making, risk communication, and the psychology of windfall gains. Stone has contributed significantly to understanding risk-taking behavior, decision-making for oneself versus others, and the effects of various types of feedback on judgment accuracy. He has published work in *Organizational Behavior and Human Decision Processes*, *Journal of Experimental Psychology: Applied*, and *Risk Analysis*, among others. He has been funded by the National Science Foundation and the National Cancer Institute. He has served on the editorial boards of the *Journal of Experimental Psychology: Applied* and *Psychological Science*, and as a reviewer for journals such as *Acta Psychologica* and *Journal of Personality and Social Psychology*. He has published countless articles and chapters in scientific journals and books. 
